#!/bin/bash
z=$(top)
while read -r z
do
   var=$var$(awk '{print "memory_usage{process=\""$12"\", pid=\""$1"\"}", $10z}');
done <<< "$z"
curl -X POST -H  "Content-Type: text/plain" --data "$var
" http://localhost:9091/metrics/job/top/instance/machine